### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property gl has not been initialized

### ISSUE THREAD

**Issue by dhakehurst** [korlibs/korge-samples#1] opened 2019-02-28 10:50 UTC
just cloned these and tried to run,
I get the above error

**Comment by dhakehurst** [comment] 2019-02-28 10:52
box2d and dragonbones give this error,
tic-tac-toe seems to work

**Comment by soywiz** [comment] 2019-03-02 09:43
Seems to be related to this: https://github.com/korlibs/korge/issues/16

**Comment by dhakehurst** [comment] 2019-03-04 08:17
I have updated to the latest release. I still get the error.
Currently trying to build korlibs from source, to test.

**Comment by soywiz** [comment] 2019-03-04 08:21
Yeah, I was not able to reproduce it, as stated in the other issue. So kept the issues open for now.

Are you running it by calling:
```
./gradlew :sample-dragonbones:runJvm
```

Which OS?

**Comment by gdepourtales** [comment] 2019-04-23 09:48
Hi all
Not sure if it helps but here's what I've done:
Set a single breakpoint on  `override lateinit var gl: KmlGl` in `GLExt`

When debugging with the breakpoint enabled everything works fine. Debugging with the breakpoint disabled throws the `Exception in thread "kotlinx.coroutines.DefaultExecutor" kotlin.UninitializedPropertyAccessException: lateinit property gl has not been initialized` each time

It looks like a concurrency issue
Hope it helps

**Comment by emign** [comment] 2019-11-19 14:29
I have that problem too. It happens sometimes and is hardly reproducible, because the EXACT same build/run works 3 out of 4 times. The other time, it throws this error. 

`15:27:49: Executing task 'openLocal'...


> Configure project :
Kotlin Multiplatform Projects are an experimental feature.

> Task :compileKotlinJvm
w: /Users/nicolaiemig/Documents/Schule/51 Unterricht/i10/Kotlin/Tests/engineEmi/src/Main.kt: (12, 9): Variable 'meinRechteck' is never used
w: /Users/nicolaiemig/Documents/Schule/51 Unterricht/i10/Kotlin/Tests/engineEmi/src/Main.kt: (13, 9): Variable 'meineGerade' is never used

> Task :genResources UP-TO-DATE
> Task :jvmProcessResources UP-TO-DATE
> Task :jvmMainClasses
> Task :compileTestKotlinJvm NO-SOURCE
> Task :genTestResources UP-TO-DATE
> Task :jvmTestProcessResources NO-SOURCE
> Task :jvmTestClasses UP-TO-DATE

> Task :runJvm
configureLoggerFromProperties:
Couldn't load Klogger configuration LocalVfs[/Users/nicolaiemig/Documents/Schule/51 Unterricht/i10/Kotlin/Tests/engineEmi/klogger.properties] : /Users/nicolaiemig/Documents/Schule/51 Unterricht/i10/Kotlin/Tests/engineEmi/klogger.properties (No such file or directory)
2019-11-19 15:27:55.327 java[5654:243039] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff3616f6ef -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 371
	1   AppKit                              0x00007fff3616cbc1 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	2   AppKit                              0x00007fff3616c633 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	3   libnativewindow_macosx.jnilib       0x00000001302133fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
	4   ???                                 0x00000001126e0667 0x0 + 4604167783
)
kotlin.UninitializedPropertyAccessException: lateinit property gl has not been initialized
	at com.soywiz.korag.AGAwtBase.getGl(GLExt.kt:46)
	at com.soywiz.korag.AGOpengl$GlBuffer.<init>(OpenglAG.kt:521)
	at com.soywiz.korag.AGOpengl.createBuffer(OpenglAG.kt:26)
	at com.soywiz.korag.AG.createVertexBuffer(AG.kt:404)
	at com.soywiz.korge.render.BatchBuilder2D.<init>(BatchBuilder2D.kt:42)
	at com.soywiz.korge.render.BatchBuilder2D.<init>(BatchBuilder2D.kt:15)
	at com.soywiz.korge.render.RenderContext.<init>(RenderContext.kt:18)
	at com.soywiz.korge.view.Views.<init>(Views.kt:61)
	at com.soywiz.korge.Korge$invoke$2.invokeSuspend(Korge.kt:416)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:83)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1.loop(DefaultGameWindowJvm.kt:381)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1$loop$1.invokeSuspend(DefaultGameWindowJvm.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:185)
	at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:22)
	at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:272)
	at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:261)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:218)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:227)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:299)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.kt:298)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "kotlinx.coroutines.DefaultExecutor" kotlin.UninitializedPropertyAccessException: lateinit property gl has not been initialized
	at com.soywiz.korag.AGAwtBase.getGl(GLExt.kt:46)
	at com.soywiz.korag.AGOpengl$GlBuffer.<init>(OpenglAG.kt:521)
	at com.soywiz.korag.AGOpengl.createBuffer(OpenglAG.kt:26)
	at com.soywiz.korag.AG.createVertexBuffer(AG.kt:404)
	at com.soywiz.korge.render.BatchBuilder2D.<init>(BatchBuilder2D.kt:42)
	at com.soywiz.korge.render.BatchBuilder2D.<init>(BatchBuilder2D.kt:15)
	at com.soywiz.korge.render.RenderContext.<init>(RenderContext.kt:18)
	at com.soywiz.korge.view.Views.<init>(Views.kt:61)
	at com.soywiz.korge.Korge$invoke$2.invokeSuspend(Korge.kt:416)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:83)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1.loop(DefaultGameWindowJvm.kt:381)
	at com.soywiz.korgw.DefaultGameWindowJvmKt$DefaultGameWindow$1$loop$1.invokeSuspend(DefaultGameWindowJvm.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:185)
	at kotlinx.coroutines.ResumeModeKt.resumeMode(ResumeMode.kt:22)
	at kotlinx.coroutines.DispatchedKt.resume(Dispatched.kt:272)
	at kotlinx.coroutines.DispatchedKt.dispatch(Dispatched.kt:261)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:218)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:227)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:299)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.kt:298)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by emign** [comment] 2019-11-19 14:47
I made a video that shows, that the error is thrown sometimes but not always (even without changing anything) when building/running

https://youtu.be/_XpvgJQ-KBA

**Comment by soywiz** [comment] 2019-12-01 14:27
This should be fixed already. Try with Korge 1.4.2. Feel free to reopen if you can still reproduce it.

**Closed by soywiz** 2019-12-01 14:27 UTC
Labels: bug
